ci(deploy): build package before publishing
If you don't build the artifacts beforehand, you'll end up with:

```
Error:  Failed to execute goal
com.google.cloud.tools:jib-maven-plugin:3.3.1:build (default-cli) on
project camunda-platform-rest-api: Obtaining project build output files
failed; make sure you have compiled your project before trying to build
the image. (Did you accidentally run "mvn clean jib:build" instead of
"mvn clean compile jib:build"?):
/home/runner/work/camunda-platform-rest-api/camunda-platform-rest-api/target/classes
-> [Help 1]
```