fix: deal with spring 6 exception handling
Seems that validation message changed when a required body parameter is
missing. The current exception has no knowledge of the property name,
only that an NPE happened. Sadly the message leaks Java related concepts
like class names.

I hope to find a better solution to spring's crappy validation
mechanism.

The failing test:
```
Error:  Failures:
Error:    JobControllerTests.putStatusShouldRejectCompletedWithoutStatus:223
Expecting actual:
  "{"data":null,"error":"ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Failed to read request', instance='null', properties='null']"}"
to contain:
  "Parameter specified as non-null is null"
```